com:
  lruikmy:
    name: zhangsan
	
eureka:
  client:
    service-url:
      defaultZone: http://www.eureka1.com:8080/eureka/,http://www.eureka2.com:8081/eureka/

---
server:
  port: 9090
spring:
  profiles: provider
  application:
    name: user-provider

---
server:
  port: 6061
spring:
  profiles: consumer
  application:
    name: consumer-feign
feign:
  hystrix:
    enabled: true

